language: python

python:
  - "3.6"

service:
  - postgresql

addons:
  postgresql: '9.6'
  code_climate:
    repo_token: "e3b243c35c4f77914807ed9d81a4b5b6ef97475c5006e921a5688fb76f915317"

install:
  - pip3 install -r requirements.txt
  - pip3 install coverage
  - pip3 install coveralls
  - pip3 install codeclimate-test-reporter

cache:
  directories:
    - $HOME/.cache/pip

before_script:
  - export DB_NAME="seven_eleven"
  - psql -c 'create database seven_eleven;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - python -m pytest
  - py.test --cov-report term --cov=.

after_script:
  - coveralls

after_sucess:
  - CODECLIMATE_REPO_TOKEN=e3b243c35c4f77914807ed9d81a4b5b6ef97475c5006e921a5688fb76f915317 codeclimate-test-reporter